name: Generate Keystore
on: workflow_dispatch

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Keystore
        run: |
          keytool -genkeypair -v -keystore release.keystore -keyalg RSA -keysize 2048 -validity 10000 -alias gpspy-key -storepass GPSPY-Store-2026! -keypass GPSPY-Key-2026! -dname 'CN=GPSPY, OU=Dev, O=J7F9, L=Taipei, ST=Taipei, C=TW'
          echo 'BASE64_KEYSTORE=' >> \

      - name: Output Base64 String
        run: |
          echo '--- COPY THIS BASE64 STRING ---'
          echo \\\
          echo '-------------------------------'